services:
  Pest\Drift\PHPUnit\ClassMethod\MethodToPestTestRector: ~
  Pest\Drift\PHPUnit\Class_\TraitUsesToUsesRector: ~

  Pest\Drift\PHPUnit\ClassMethod\SetUpToBeforeEachRector: ~
  Pest\Drift\PHPUnit\ClassMethod\TearDownToAfterEachRector: ~
  Pest\Drift\PHPUnit\ClassMethod\AfterClassToAfterAllRector: ~
  Pest\Drift\PHPUnit\ClassMethod\BeforeClassToBeforeAllRector: ~

  Pest\Drift\PHPUnit\Class_\PhpDocGroupOnClassToFileScopeGroupRector: ~
  Pest\Drift\PHPUnit\ClassMethod\DataProviderRector: ~
  Pest\Drift\PHPUnit\ClassMethod\HelperMethodRector: ~
  Pest\Drift\PHPUnit\Class_\CustomTestCaseToUsesRector: ~

  Pest\Drift\PHPUnit\Class_\RemovePHPUnitClassRector: ~
  Pest\Drift\Pest\PestCollectingRector: ~


  Pest\Drift\PestCollector: ~
